name: Release

on:
  push:
    tags: ["*"]

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  package:
    name: Packages
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install pypa/build
        run: >-
          python3 -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        run: >-
          python3 -m
          build
          --sdist
          --wheel
          --outdir dist/

  deploy:
    name: Deploy
    environment: Deployment
    needs: [ci, package]
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Download packages built
        uses: actions/download-artifact@v3
        with:
          name: Packages
          path: dist

      - name: Upload package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
